version: "2"
services:
    www:
        build: .
        ports: 
            - "8801:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.24
        ports: 
            - "3301:3306"
        environment:
            MYSQL_DATABASE: testapi
            MYSQL_USER: testuser
            MYSQL_PASSWORD: passw0rd
            MYSQL_ROOT_PASSWORD: passw0rd99
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - /var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8802:80
        environment:
            MYSQL_USER: testuser
            MYSQL_PASSWORD: passw0rd
            MYSQL_ROOT_PASSWORD: passw0rd99
